import React, { useEffect, useState } from "react";
import {
  collection,
  query,
  orderBy,
  limit,
  startAfter,
  getDocs,
} from "firebase/firestore";
import { db } from "../../firebase";

const PAGE_SIZE = 10;

export default function GeoAlerts() {
  const [alerts, setAlerts] = useState([]);
  const [lastDoc, setLastDoc] = useState(null);
  const [hasMore, setHasMore] = useState(true);
  const [loading, setLoading] = useState(false);

  /* ======================
     LOAD GEO ALERTS
  ====================== */
  const loadAlerts = async (reset = false) => {
    try {
      setLoading(true);

      let q = query(
        collection(db, "merchant_alerts"), // or geo_events
        orderBy("lastSent", "desc"),
        limit(PAGE_SIZE)
      );

      if (!reset && lastDoc) {
        q = query(
          collection(db, "merchant_alerts"),
          orderBy("lastSent", "desc"),
          startAfter(lastDoc),
          limit(PAGE_SIZE)
        );
      }

      const snap = await getDocs(q);

      const data = snap.docs.map((d) => ({
        id: d.id,
        ...d.data(),
      }));

      setAlerts(reset ? data : [...alerts, ...data]);
      setLastDoc(snap.docs[snap.docs.length - 1] || null);
      setHasMore(snap.docs.length === PAGE_SIZE);
    } catch (err) {
      console.error("Load geo alerts error:", err);
      alert("Failed to load geo alerts");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAlerts(true);
    // eslint-disable-next-line
  }, []);

  return (
    <div style={{ padding: 20 }}>
      <h2>Geo Alerts</h2>

      <p style={{ color: "#555" }}>
        Customer proximity alerts generated by GeoFence
      </p>

      {/* TABLE */}
      <table border="1" width="100%" cellPadding="8">
        <thead>
          <tr>
            <th>Merchant ID</th>
            <th>Customer ID</th>
            <th>Distance (m)</th>
            <th>Alert Time</th>
          </tr>
        </thead>
        <tbody>
          {alerts.map((a) => (
            <tr key={a.id}>
              <td>{a.merchantId}</td>
              <td>{a.customerId}</td>
              <td>{Math.round(a.distance || 0)}</td>
              <td>
                {a.lastSent
                  ? new Date(
                      a.lastSent.seconds * 1000
                    ).toLocaleString()
                  : "-"}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {alerts.length === 0 && !loading && (
        <p>No geo alerts found.</p>
      )}

      {/* PAGINATION */}
      {hasMore && (
        <button
          disabled={loading}
          onClick={() => loadAlerts(false)}
        >
          {loading ? "Loading..." : "Load More"}
        </button>
      )}
    </div>
  );
}
